#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Thue_Oto.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ThueOto1")]
	public partial class DB_Thue_OtoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertXeDichVu(XeDichVu instance);
    partial void UpdateXeDichVu(XeDichVu instance);
    partial void DeleteXeDichVu(XeDichVu instance);
    partial void InsertBangGia(BangGia instance);
    partial void UpdateBangGia(BangGia instance);
    partial void DeleteBangGia(BangGia instance);
    partial void InsertHangXe(HangXe instance);
    partial void UpdateHangXe(HangXe instance);
    partial void DeleteHangXe(HangXe instance);
    partial void InsertHinhThucThue(HinhThucThue instance);
    partial void UpdateHinhThucThue(HinhThucThue instance);
    partial void DeleteHinhThucThue(HinhThucThue instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiChoNgoi(LoaiChoNgoi instance);
    partial void UpdateLoaiChoNgoi(LoaiChoNgoi instance);
    partial void DeleteLoaiChoNgoi(LoaiChoNgoi instance);
    partial void InsertLoaiHinhThue(LoaiHinhThue instance);
    partial void UpdateLoaiHinhThue(LoaiHinhThue instance);
    partial void DeleteLoaiHinhThue(LoaiHinhThue instance);
    partial void InsertPhieuDatXe(PhieuDatXe instance);
    partial void UpdatePhieuDatXe(PhieuDatXe instance);
    partial void DeletePhieuDatXe(PhieuDatXe instance);
    #endregion
		
		public DB_Thue_OtoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ThueOto1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Thue_OtoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Thue_OtoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Thue_OtoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_Thue_OtoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<XeDichVu> XeDichVus
		{
			get
			{
				return this.GetTable<XeDichVu>();
			}
		}
		
		public System.Data.Linq.Table<BangGia> BangGias
		{
			get
			{
				return this.GetTable<BangGia>();
			}
		}
		
		public System.Data.Linq.Table<HangXe> HangXes
		{
			get
			{
				return this.GetTable<HangXe>();
			}
		}
		
		public System.Data.Linq.Table<HinhThucThue> HinhThucThues
		{
			get
			{
				return this.GetTable<HinhThucThue>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiChoNgoi> LoaiChoNgois
		{
			get
			{
				return this.GetTable<LoaiChoNgoi>();
			}
		}
		
		public System.Data.Linq.Table<LoaiHinhThue> LoaiHinhThues
		{
			get
			{
				return this.GetTable<LoaiHinhThue>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDatXe> PhieuDatXes
		{
			get
			{
				return this.GetTable<PhieuDatXe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin
	{
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _MatKhauCap2;
		
		public Admin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this._TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauCap2", DbType="VarChar(50)")]
		public string MatKhauCap2
		{
			get
			{
				return this._MatKhauCap2;
			}
			set
			{
				if ((this._MatKhauCap2 != value))
				{
					this._MatKhauCap2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.XeDichVu")]
	public partial class XeDichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDVXe;
		
		private int _MaChoNgoi;
		
		private int _MaHang;
		
		private string _TenXe;
		
		private string _ThongTinHopSo;
		
		private string _NhienLieuTP;
		
		private string _NhienLieuNTP;
		
		private string _DoiXe;
		
		private string _BienSoXe;
		
		private string _MauXe;
		
		private string _TenHinh;
		
		private bool _TinhTrang;
		
		private System.DateTime _NgayCapNhat;
		
		private string _DongXe;
		
		private EntitySet<BangGia> _BangGias;
		
		private EntitySet<PhieuDatXe> _PhieuDatXes;
		
		private EntityRef<HangXe> _HangXe;
		
		private EntityRef<LoaiChoNgoi> _LoaiChoNgoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVXeChanging(int value);
    partial void OnMaDVXeChanged();
    partial void OnMaChoNgoiChanging(int value);
    partial void OnMaChoNgoiChanged();
    partial void OnMaHangChanging(int value);
    partial void OnMaHangChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnThongTinHopSoChanging(string value);
    partial void OnThongTinHopSoChanged();
    partial void OnNhienLieuTPChanging(string value);
    partial void OnNhienLieuTPChanged();
    partial void OnNhienLieuNTPChanging(string value);
    partial void OnNhienLieuNTPChanged();
    partial void OnDoiXeChanging(string value);
    partial void OnDoiXeChanged();
    partial void OnBienSoXeChanging(string value);
    partial void OnBienSoXeChanged();
    partial void OnMauXeChanging(string value);
    partial void OnMauXeChanged();
    partial void OnTenHinhChanging(string value);
    partial void OnTenHinhChanged();
    partial void OnTinhTrangChanging(bool value);
    partial void OnTinhTrangChanged();
    partial void OnNgayCapNhatChanging(System.DateTime value);
    partial void OnNgayCapNhatChanged();
    partial void OnDongXeChanging(string value);
    partial void OnDongXeChanged();
    #endregion
		
		public XeDichVu()
		{
			this._BangGias = new EntitySet<BangGia>(new Action<BangGia>(this.attach_BangGias), new Action<BangGia>(this.detach_BangGias));
			this._PhieuDatXes = new EntitySet<PhieuDatXe>(new Action<PhieuDatXe>(this.attach_PhieuDatXes), new Action<PhieuDatXe>(this.detach_PhieuDatXes));
			this._HangXe = default(EntityRef<HangXe>);
			this._LoaiChoNgoi = default(EntityRef<LoaiChoNgoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDVXe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaDVXe
		{
			get
			{
				return this._MaDVXe;
			}
			set
			{
				if ((this._MaDVXe != value))
				{
					this.OnMaDVXeChanging(value);
					this.SendPropertyChanging();
					this._MaDVXe = value;
					this.SendPropertyChanged("MaDVXe");
					this.OnMaDVXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChoNgoi", DbType="Int NOT NULL")]
		public int MaChoNgoi
		{
			get
			{
				return this._MaChoNgoi;
			}
			set
			{
				if ((this._MaChoNgoi != value))
				{
					if (this._LoaiChoNgoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._MaChoNgoi = value;
					this.SendPropertyChanged("MaChoNgoi");
					this.OnMaChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="Int NOT NULL")]
		public int MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					if (this._HangXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThongTinHopSo", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string ThongTinHopSo
		{
			get
			{
				return this._ThongTinHopSo;
			}
			set
			{
				if ((this._ThongTinHopSo != value))
				{
					this.OnThongTinHopSoChanging(value);
					this.SendPropertyChanging();
					this._ThongTinHopSo = value;
					this.SendPropertyChanged("ThongTinHopSo");
					this.OnThongTinHopSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhienLieuTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhienLieuTP
		{
			get
			{
				return this._NhienLieuTP;
			}
			set
			{
				if ((this._NhienLieuTP != value))
				{
					this.OnNhienLieuTPChanging(value);
					this.SendPropertyChanging();
					this._NhienLieuTP = value;
					this.SendPropertyChanged("NhienLieuTP");
					this.OnNhienLieuTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhienLieuNTP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NhienLieuNTP
		{
			get
			{
				return this._NhienLieuNTP;
			}
			set
			{
				if ((this._NhienLieuNTP != value))
				{
					this.OnNhienLieuNTPChanging(value);
					this.SendPropertyChanging();
					this._NhienLieuNTP = value;
					this.SendPropertyChanged("NhienLieuNTP");
					this.OnNhienLieuNTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoiXe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string DoiXe
		{
			get
			{
				return this._DoiXe;
			}
			set
			{
				if ((this._DoiXe != value))
				{
					this.OnDoiXeChanging(value);
					this.SendPropertyChanging();
					this._DoiXe = value;
					this.SendPropertyChanged("DoiXe");
					this.OnDoiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BienSoXe", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string BienSoXe
		{
			get
			{
				return this._BienSoXe;
			}
			set
			{
				if ((this._BienSoXe != value))
				{
					this.OnBienSoXeChanging(value);
					this.SendPropertyChanging();
					this._BienSoXe = value;
					this.SendPropertyChanged("BienSoXe");
					this.OnBienSoXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MauXe
		{
			get
			{
				return this._MauXe;
			}
			set
			{
				if ((this._MauXe != value))
				{
					this.OnMauXeChanging(value);
					this.SendPropertyChanging();
					this._MauXe = value;
					this.SendPropertyChanged("MauXe");
					this.OnMauXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHinh", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenHinh
		{
			get
			{
				return this._TenHinh;
			}
			set
			{
				if ((this._TenHinh != value))
				{
					this.OnTenHinhChanging(value);
					this.SendPropertyChanging();
					this._TenHinh = value;
					this.SendPropertyChanged("TenHinh");
					this.OnTenHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit NOT NULL")]
		public bool TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime NOT NULL")]
		public System.DateTime NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongXe", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DongXe
		{
			get
			{
				return this._DongXe;
			}
			set
			{
				if ((this._DongXe != value))
				{
					this.OnDongXeChanging(value);
					this.SendPropertyChanging();
					this._DongXe = value;
					this.SendPropertyChanged("DongXe");
					this.OnDongXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XeDichVu_BangGia", Storage="_BangGias", ThisKey="MaDVXe", OtherKey="MaDVXe")]
		public EntitySet<BangGia> BangGias
		{
			get
			{
				return this._BangGias;
			}
			set
			{
				this._BangGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XeDichVu_PhieuDatXe", Storage="_PhieuDatXes", ThisKey="MaDVXe", OtherKey="MaDVXe")]
		public EntitySet<PhieuDatXe> PhieuDatXes
		{
			get
			{
				return this._PhieuDatXes;
			}
			set
			{
				this._PhieuDatXes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_XeDichVu", Storage="_HangXe", ThisKey="MaHang", OtherKey="MaHang", IsForeignKey=true)]
		public HangXe HangXe
		{
			get
			{
				return this._HangXe.Entity;
			}
			set
			{
				HangXe previousValue = this._HangXe.Entity;
				if (((previousValue != value) 
							|| (this._HangXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangXe.Entity = null;
						previousValue.XeDichVus.Remove(this);
					}
					this._HangXe.Entity = value;
					if ((value != null))
					{
						value.XeDichVus.Add(this);
						this._MaHang = value.MaHang;
					}
					else
					{
						this._MaHang = default(int);
					}
					this.SendPropertyChanged("HangXe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiChoNgoi_XeDichVu", Storage="_LoaiChoNgoi", ThisKey="MaChoNgoi", OtherKey="MaChoNgoi", IsForeignKey=true)]
		public LoaiChoNgoi LoaiChoNgoi
		{
			get
			{
				return this._LoaiChoNgoi.Entity;
			}
			set
			{
				LoaiChoNgoi previousValue = this._LoaiChoNgoi.Entity;
				if (((previousValue != value) 
							|| (this._LoaiChoNgoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiChoNgoi.Entity = null;
						previousValue.XeDichVus.Remove(this);
					}
					this._LoaiChoNgoi.Entity = value;
					if ((value != null))
					{
						value.XeDichVus.Add(this);
						this._MaChoNgoi = value.MaChoNgoi;
					}
					else
					{
						this._MaChoNgoi = default(int);
					}
					this.SendPropertyChanged("LoaiChoNgoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.XeDichVu = this;
		}
		
		private void detach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.XeDichVu = null;
		}
		
		private void attach_PhieuDatXes(PhieuDatXe entity)
		{
			this.SendPropertyChanging();
			entity.XeDichVu = this;
		}
		
		private void detach_PhieuDatXes(PhieuDatXe entity)
		{
			this.SendPropertyChanging();
			entity.XeDichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BangGia")]
	public partial class BangGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBangGia;
		
		private int _MaDVXe;
		
		private int _MaHinhThucThue;
		
		private int _MaLoaiHinhThue;
		
		private int _BangGia1;
		
		private EntityRef<XeDichVu> _XeDichVu;
		
		private EntityRef<HinhThucThue> _HinhThucThue;
		
		private EntityRef<LoaiHinhThue> _LoaiHinhThue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBangGiaChanging(int value);
    partial void OnMaBangGiaChanged();
    partial void OnMaDVXeChanging(int value);
    partial void OnMaDVXeChanged();
    partial void OnMaHinhThucThueChanging(int value);
    partial void OnMaHinhThucThueChanged();
    partial void OnMaLoaiHinhThueChanging(int value);
    partial void OnMaLoaiHinhThueChanged();
    partial void OnBangGia1Changing(int value);
    partial void OnBangGia1Changed();
    #endregion
		
		public BangGia()
		{
			this._XeDichVu = default(EntityRef<XeDichVu>);
			this._HinhThucThue = default(EntityRef<HinhThucThue>);
			this._LoaiHinhThue = default(EntityRef<LoaiHinhThue>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDVXe", DbType="Int NOT NULL")]
		public int MaDVXe
		{
			get
			{
				return this._MaDVXe;
			}
			set
			{
				if ((this._MaDVXe != value))
				{
					if (this._XeDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVXeChanging(value);
					this.SendPropertyChanging();
					this._MaDVXe = value;
					this.SendPropertyChanged("MaDVXe");
					this.OnMaDVXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThucThue", DbType="Int NOT NULL")]
		public int MaHinhThucThue
		{
			get
			{
				return this._MaHinhThucThue;
			}
			set
			{
				if ((this._MaHinhThucThue != value))
				{
					if (this._HinhThucThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHinhThucThueChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThucThue = value;
					this.SendPropertyChanged("MaHinhThucThue");
					this.OnMaHinhThucThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinhThue", DbType="Int NOT NULL")]
		public int MaLoaiHinhThue
		{
			get
			{
				return this._MaLoaiHinhThue;
			}
			set
			{
				if ((this._MaLoaiHinhThue != value))
				{
					if (this._LoaiHinhThue.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiHinhThueChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinhThue = value;
					this.SendPropertyChanged("MaLoaiHinhThue");
					this.OnMaLoaiHinhThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="BangGia", Storage="_BangGia1", DbType="Int NOT NULL")]
		public int BangGia1
		{
			get
			{
				return this._BangGia1;
			}
			set
			{
				if ((this._BangGia1 != value))
				{
					this.OnBangGia1Changing(value);
					this.SendPropertyChanging();
					this._BangGia1 = value;
					this.SendPropertyChanged("BangGia1");
					this.OnBangGia1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XeDichVu_BangGia", Storage="_XeDichVu", ThisKey="MaDVXe", OtherKey="MaDVXe", IsForeignKey=true)]
		public XeDichVu XeDichVu
		{
			get
			{
				return this._XeDichVu.Entity;
			}
			set
			{
				XeDichVu previousValue = this._XeDichVu.Entity;
				if (((previousValue != value) 
							|| (this._XeDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XeDichVu.Entity = null;
						previousValue.BangGias.Remove(this);
					}
					this._XeDichVu.Entity = value;
					if ((value != null))
					{
						value.BangGias.Add(this);
						this._MaDVXe = value.MaDVXe;
					}
					else
					{
						this._MaDVXe = default(int);
					}
					this.SendPropertyChanged("XeDichVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThucThue_BangGia", Storage="_HinhThucThue", ThisKey="MaHinhThucThue", OtherKey="MaHinhThucThue", IsForeignKey=true)]
		public HinhThucThue HinhThucThue
		{
			get
			{
				return this._HinhThucThue.Entity;
			}
			set
			{
				HinhThucThue previousValue = this._HinhThucThue.Entity;
				if (((previousValue != value) 
							|| (this._HinhThucThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HinhThucThue.Entity = null;
						previousValue.BangGias.Remove(this);
					}
					this._HinhThucThue.Entity = value;
					if ((value != null))
					{
						value.BangGias.Add(this);
						this._MaHinhThucThue = value.MaHinhThucThue;
					}
					else
					{
						this._MaHinhThucThue = default(int);
					}
					this.SendPropertyChanged("HinhThucThue");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHinhThue_BangGia", Storage="_LoaiHinhThue", ThisKey="MaLoaiHinhThue", OtherKey="MaLoaiHinhThue", IsForeignKey=true)]
		public LoaiHinhThue LoaiHinhThue
		{
			get
			{
				return this._LoaiHinhThue.Entity;
			}
			set
			{
				LoaiHinhThue previousValue = this._LoaiHinhThue.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHinhThue.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHinhThue.Entity = null;
						previousValue.BangGias.Remove(this);
					}
					this._LoaiHinhThue.Entity = value;
					if ((value != null))
					{
						value.BangGias.Add(this);
						this._MaLoaiHinhThue = value.MaLoaiHinhThue;
					}
					else
					{
						this._MaLoaiHinhThue = default(int);
					}
					this.SendPropertyChanged("LoaiHinhThue");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangXe")]
	public partial class HangXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHang;
		
		private string _TenHang;
		
		private EntitySet<XeDichVu> _XeDichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHangChanging(int value);
    partial void OnMaHangChanged();
    partial void OnTenHangChanging(string value);
    partial void OnTenHangChanged();
    #endregion
		
		public HangXe()
		{
			this._XeDichVus = new EntitySet<XeDichVu>(new Action<XeDichVu>(this.attach_XeDichVus), new Action<XeDichVu>(this.detach_XeDichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHang", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHang
		{
			get
			{
				return this._MaHang;
			}
			set
			{
				if ((this._MaHang != value))
				{
					this.OnMaHangChanging(value);
					this.SendPropertyChanging();
					this._MaHang = value;
					this.SendPropertyChanged("MaHang");
					this.OnMaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHang", DbType="NVarChar(50)")]
		public string TenHang
		{
			get
			{
				return this._TenHang;
			}
			set
			{
				if ((this._TenHang != value))
				{
					this.OnTenHangChanging(value);
					this.SendPropertyChanging();
					this._TenHang = value;
					this.SendPropertyChanged("TenHang");
					this.OnTenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangXe_XeDichVu", Storage="_XeDichVus", ThisKey="MaHang", OtherKey="MaHang")]
		public EntitySet<XeDichVu> XeDichVus
		{
			get
			{
				return this._XeDichVus;
			}
			set
			{
				this._XeDichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XeDichVus(XeDichVu entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = this;
		}
		
		private void detach_XeDichVus(XeDichVu entity)
		{
			this.SendPropertyChanging();
			entity.HangXe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhThucThue")]
	public partial class HinhThucThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHinhThucThue;
		
		private string _TenHInhThucThue;
		
		private EntitySet<BangGia> _BangGias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHinhThucThueChanging(int value);
    partial void OnMaHinhThucThueChanged();
    partial void OnTenHInhThucThueChanging(string value);
    partial void OnTenHInhThucThueChanged();
    #endregion
		
		public HinhThucThue()
		{
			this._BangGias = new EntitySet<BangGia>(new Action<BangGia>(this.attach_BangGias), new Action<BangGia>(this.detach_BangGias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHinhThucThue", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHinhThucThue
		{
			get
			{
				return this._MaHinhThucThue;
			}
			set
			{
				if ((this._MaHinhThucThue != value))
				{
					this.OnMaHinhThucThueChanging(value);
					this.SendPropertyChanging();
					this._MaHinhThucThue = value;
					this.SendPropertyChanged("MaHinhThucThue");
					this.OnMaHinhThucThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHInhThucThue", DbType="NVarChar(50)")]
		public string TenHInhThucThue
		{
			get
			{
				return this._TenHInhThucThue;
			}
			set
			{
				if ((this._TenHInhThucThue != value))
				{
					this.OnTenHInhThucThueChanging(value);
					this.SendPropertyChanging();
					this._TenHInhThucThue = value;
					this.SendPropertyChanged("TenHInhThucThue");
					this.OnTenHInhThucThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HinhThucThue_BangGia", Storage="_BangGias", ThisKey="MaHinhThucThue", OtherKey="MaHinhThucThue")]
		public EntitySet<BangGia> BangGias
		{
			get
			{
				return this._BangGias;
			}
			set
			{
				this._BangGias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.HinhThucThue = this;
		}
		
		private void detach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.HinhThucThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private int _MaPhieuDatXe;
		
		private int _MaBangGia;
		
		private System.DateTime _NgayTra;
		
		private System.Nullable<int> _SoNgayThue;
		
		private EntityRef<PhieuDatXe> _PhieuDatXe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaPhieuDatXeChanging(int value);
    partial void OnMaPhieuDatXeChanged();
    partial void OnMaBangGiaChanging(int value);
    partial void OnMaBangGiaChanged();
    partial void OnNgayTraChanging(System.DateTime value);
    partial void OnNgayTraChanged();
    partial void OnSoNgayThueChanging(System.Nullable<int> value);
    partial void OnSoNgayThueChanged();
    #endregion
		
		public HoaDon()
		{
			this._PhieuDatXe = default(EntityRef<PhieuDatXe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDatXe", DbType="Int NOT NULL")]
		public int MaPhieuDatXe
		{
			get
			{
				return this._MaPhieuDatXe;
			}
			set
			{
				if ((this._MaPhieuDatXe != value))
				{
					if (this._PhieuDatXe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuDatXeChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDatXe = value;
					this.SendPropertyChanged("MaPhieuDatXe");
					this.OnMaPhieuDatXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBangGia", DbType="Int NOT NULL")]
		public int MaBangGia
		{
			get
			{
				return this._MaBangGia;
			}
			set
			{
				if ((this._MaBangGia != value))
				{
					this.OnMaBangGiaChanging(value);
					this.SendPropertyChanging();
					this._MaBangGia = value;
					this.SendPropertyChanged("MaBangGia");
					this.OnMaBangGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="DateTime NOT NULL")]
		public System.DateTime NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNgayThue", DbType="Int")]
		public System.Nullable<int> SoNgayThue
		{
			get
			{
				return this._SoNgayThue;
			}
			set
			{
				if ((this._SoNgayThue != value))
				{
					this.OnSoNgayThueChanging(value);
					this.SendPropertyChanging();
					this._SoNgayThue = value;
					this.SendPropertyChanged("SoNgayThue");
					this.OnSoNgayThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDatXe_HoaDon", Storage="_PhieuDatXe", ThisKey="MaPhieuDatXe", OtherKey="MaPhieuDatXe", IsForeignKey=true)]
		public PhieuDatXe PhieuDatXe
		{
			get
			{
				return this._PhieuDatXe.Entity;
			}
			set
			{
				PhieuDatXe previousValue = this._PhieuDatXe.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDatXe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDatXe.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._PhieuDatXe.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._MaPhieuDatXe = value.MaPhieuDatXe;
					}
					else
					{
						this._MaPhieuDatXe = default(int);
					}
					this.SendPropertyChanged("PhieuDatXe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKH;
		
		private string _TenKH;
		
		private string _DiaChi;
		
		private string _DienThoai;
		
		private string _TaiKhoanKH;
		
		private string _MatKhauKH;
		
		private EntitySet<PhieuDatXe> _PhieuDatXes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTaiKhoanKHChanging(string value);
    partial void OnTaiKhoanKHChanged();
    partial void OnMatKhauKHChanging(string value);
    partial void OnMatKhauKHChanged();
    #endregion
		
		public KhachHang()
		{
			this._PhieuDatXes = new EntitySet<PhieuDatXe>(new Action<PhieuDatXe>(this.attach_PhieuDatXes), new Action<PhieuDatXe>(this.detach_PhieuDatXes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(100)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(20)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanKH", DbType="VarChar(50)")]
		public string TaiKhoanKH
		{
			get
			{
				return this._TaiKhoanKH;
			}
			set
			{
				if ((this._TaiKhoanKH != value))
				{
					this.OnTaiKhoanKHChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanKH = value;
					this.SendPropertyChanged("TaiKhoanKH");
					this.OnTaiKhoanKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauKH", DbType="VarChar(50)")]
		public string MatKhauKH
		{
			get
			{
				return this._MatKhauKH;
			}
			set
			{
				if ((this._MatKhauKH != value))
				{
					this.OnMatKhauKHChanging(value);
					this.SendPropertyChanging();
					this._MatKhauKH = value;
					this.SendPropertyChanged("MatKhauKH");
					this.OnMatKhauKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatXe", Storage="_PhieuDatXes", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<PhieuDatXe> PhieuDatXes
		{
			get
			{
				return this._PhieuDatXes;
			}
			set
			{
				this._PhieuDatXes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDatXes(PhieuDatXe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_PhieuDatXes(PhieuDatXe entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiChoNgoi")]
	public partial class LoaiChoNgoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChoNgoi;
		
		private string _SoChoNgoi;
		
		private EntitySet<XeDichVu> _XeDichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChoNgoiChanging(int value);
    partial void OnMaChoNgoiChanged();
    partial void OnSoChoNgoiChanging(string value);
    partial void OnSoChoNgoiChanged();
    #endregion
		
		public LoaiChoNgoi()
		{
			this._XeDichVus = new EntitySet<XeDichVu>(new Action<XeDichVu>(this.attach_XeDichVus), new Action<XeDichVu>(this.detach_XeDichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChoNgoi", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaChoNgoi
		{
			get
			{
				return this._MaChoNgoi;
			}
			set
			{
				if ((this._MaChoNgoi != value))
				{
					this.OnMaChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._MaChoNgoi = value;
					this.SendPropertyChanged("MaChoNgoi");
					this.OnMaChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChoNgoi", DbType="NVarChar(20)")]
		public string SoChoNgoi
		{
			get
			{
				return this._SoChoNgoi;
			}
			set
			{
				if ((this._SoChoNgoi != value))
				{
					this.OnSoChoNgoiChanging(value);
					this.SendPropertyChanging();
					this._SoChoNgoi = value;
					this.SendPropertyChanged("SoChoNgoi");
					this.OnSoChoNgoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiChoNgoi_XeDichVu", Storage="_XeDichVus", ThisKey="MaChoNgoi", OtherKey="MaChoNgoi")]
		public EntitySet<XeDichVu> XeDichVus
		{
			get
			{
				return this._XeDichVus;
			}
			set
			{
				this._XeDichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_XeDichVus(XeDichVu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiChoNgoi = this;
		}
		
		private void detach_XeDichVus(XeDichVu entity)
		{
			this.SendPropertyChanging();
			entity.LoaiChoNgoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiHinhThue")]
	public partial class LoaiHinhThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiHinhThue;
		
		private string _TenLoaiHinhThue;
		
		private EntitySet<BangGia> _BangGias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiHinhThueChanging(int value);
    partial void OnMaLoaiHinhThueChanged();
    partial void OnTenLoaiHinhThueChanging(string value);
    partial void OnTenLoaiHinhThueChanged();
    #endregion
		
		public LoaiHinhThue()
		{
			this._BangGias = new EntitySet<BangGia>(new Action<BangGia>(this.attach_BangGias), new Action<BangGia>(this.detach_BangGias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiHinhThue", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaLoaiHinhThue
		{
			get
			{
				return this._MaLoaiHinhThue;
			}
			set
			{
				if ((this._MaLoaiHinhThue != value))
				{
					this.OnMaLoaiHinhThueChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiHinhThue = value;
					this.SendPropertyChanged("MaLoaiHinhThue");
					this.OnMaLoaiHinhThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiHinhThue", DbType="NVarChar(50)")]
		public string TenLoaiHinhThue
		{
			get
			{
				return this._TenLoaiHinhThue;
			}
			set
			{
				if ((this._TenLoaiHinhThue != value))
				{
					this.OnTenLoaiHinhThueChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiHinhThue = value;
					this.SendPropertyChanged("TenLoaiHinhThue");
					this.OnTenLoaiHinhThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHinhThue_BangGia", Storage="_BangGias", ThisKey="MaLoaiHinhThue", OtherKey="MaLoaiHinhThue")]
		public EntitySet<BangGia> BangGias
		{
			get
			{
				return this._BangGias;
			}
			set
			{
				this._BangGias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHinhThue = this;
		}
		
		private void detach_BangGias(BangGia entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHinhThue = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDatXe")]
	public partial class PhieuDatXe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhieuDatXe;
		
		private int _MaKH;
		
		private System.DateTime _NgayDinhThue;
		
		private System.DateTime _NgayDinhTra;
		
		private int _TienCoc;
		
		private int _MaDVXe;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<XeDichVu> _XeDichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuDatXeChanging(int value);
    partial void OnMaPhieuDatXeChanged();
    partial void OnMaKHChanging(int value);
    partial void OnMaKHChanged();
    partial void OnNgayDinhThueChanging(System.DateTime value);
    partial void OnNgayDinhThueChanged();
    partial void OnNgayDinhTraChanging(System.DateTime value);
    partial void OnNgayDinhTraChanged();
    partial void OnTienCocChanging(int value);
    partial void OnTienCocChanged();
    partial void OnMaDVXeChanging(int value);
    partial void OnMaDVXeChanged();
    #endregion
		
		public PhieuDatXe()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._XeDichVu = default(EntityRef<XeDichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuDatXe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaPhieuDatXe
		{
			get
			{
				return this._MaPhieuDatXe;
			}
			set
			{
				if ((this._MaPhieuDatXe != value))
				{
					this.OnMaPhieuDatXeChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuDatXe = value;
					this.SendPropertyChanged("MaPhieuDatXe");
					this.OnMaPhieuDatXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="Int NOT NULL")]
		public int MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDinhThue", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDinhThue
		{
			get
			{
				return this._NgayDinhThue;
			}
			set
			{
				if ((this._NgayDinhThue != value))
				{
					this.OnNgayDinhThueChanging(value);
					this.SendPropertyChanging();
					this._NgayDinhThue = value;
					this.SendPropertyChanged("NgayDinhThue");
					this.OnNgayDinhThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDinhTra", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDinhTra
		{
			get
			{
				return this._NgayDinhTra;
			}
			set
			{
				if ((this._NgayDinhTra != value))
				{
					this.OnNgayDinhTraChanging(value);
					this.SendPropertyChanging();
					this._NgayDinhTra = value;
					this.SendPropertyChanged("NgayDinhTra");
					this.OnNgayDinhTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TienCoc", DbType="Int NOT NULL")]
		public int TienCoc
		{
			get
			{
				return this._TienCoc;
			}
			set
			{
				if ((this._TienCoc != value))
				{
					this.OnTienCocChanging(value);
					this.SendPropertyChanging();
					this._TienCoc = value;
					this.SendPropertyChanged("TienCoc");
					this.OnTienCocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDVXe", DbType="Int NOT NULL")]
		public int MaDVXe
		{
			get
			{
				return this._MaDVXe;
			}
			set
			{
				if ((this._MaDVXe != value))
				{
					if (this._XeDichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVXeChanging(value);
					this.SendPropertyChanging();
					this._MaDVXe = value;
					this.SendPropertyChanged("MaDVXe");
					this.OnMaDVXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDatXe_HoaDon", Storage="_HoaDons", ThisKey="MaPhieuDatXe", OtherKey="MaPhieuDatXe")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_PhieuDatXe", Storage="_KhachHang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.PhieuDatXes.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.PhieuDatXes.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="XeDichVu_PhieuDatXe", Storage="_XeDichVu", ThisKey="MaDVXe", OtherKey="MaDVXe", IsForeignKey=true)]
		public XeDichVu XeDichVu
		{
			get
			{
				return this._XeDichVu.Entity;
			}
			set
			{
				XeDichVu previousValue = this._XeDichVu.Entity;
				if (((previousValue != value) 
							|| (this._XeDichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._XeDichVu.Entity = null;
						previousValue.PhieuDatXes.Remove(this);
					}
					this._XeDichVu.Entity = value;
					if ((value != null))
					{
						value.PhieuDatXes.Add(this);
						this._MaDVXe = value.MaDVXe;
					}
					else
					{
						this._MaDVXe = default(int);
					}
					this.SendPropertyChanged("XeDichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDatXe = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDatXe = null;
		}
	}
}
#pragma warning restore 1591
